In [2]:
import polars as pl
import numpy as np

In [3]:
df = pl.read_parquet("/Users/maxwoolf/Downloads/mtg_embeddings_2d-3.parquet")

df

shape: (32_254, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ name      ┆ scryfallI ┆ manaCost  ┆ type      ┆ … ┆ sets      ┆ embedding ┆ x_2d      ┆ y_2d     │
│ ---       ┆ d         ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ list[enum ┆ array[f32 ┆ f32       ┆ f32      │
│           ┆ str       ┆           ┆           ┆   ┆ ]         ┆ , 768]    ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ "Ach!     ┆ 84f2c8f5- ┆ {2}{R}{R} ┆ Enchantme ┆ … ┆ ["UNH"]   ┆ [0.021458 ┆ -0.261871 ┆ 2.217163 │
│ Hans,     ┆ 8e11-4639 ┆ {G}{G}    ┆ nt        ┆   ┆           ┆ , -0.0361 ┆           ┆          │
│ Run!"     ┆ -b7de-00e ┆           ┆           ┆   ┆           ┆ 02, …     ┆           ┆          │
│           ┆ 4a2…      ┆           ┆           ┆   ┆           ┆ -0.006…   ┆           ┆          │
│ "Brims"   ┆ 68832214- ┆ {3}{W}{B} ┆ Legendary ┆ … ┆ ["UNF"]   ┆ [0.000261 ┆ 0.045746  ┆ -0.99035 │
│ Barone,   ┆ 2943-4253 ┆           ┆ Creature  ┆   ┆           ┆ ,         ┆           ┆ 6        │
│ Midway    ┆ -8884-ffa ┆           ┆ — Human   ┆   ┆           ┆ 0.025207, ┆           ┆          │
│ Mobster   ┆ 490…      ┆           ┆ Rog…      ┆   ┆           ┆ …         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.00564…  ┆           ┆          │
│ "Lifetime ┆ 42293306- ┆ {B}       ┆ Creature  ┆ … ┆ ["UNF"]   ┆ [-0.00446 ┆ -1.034943 ┆ 0.165527 │
│ " Pass    ┆ aaea-4542 ┆           ┆ — Zombie  ┆   ┆           ┆ 7, -0.016 ┆           ┆          │
│ Holder    ┆ -8df4-813 ┆           ┆ Guest     ┆   ┆           ┆ 707, …    ┆           ┆          │
│           ┆ 823…      ┆           ┆           ┆   ┆           ┆ 0.001…    ┆           ┆          │
│ "Name     ┆ fd1442b4- ┆ {2}{R}    ┆ Creature  ┆ … ┆ ["UNF"]   ┆ [-0.03243 ┆ -3.05658  ┆ -2.96411 │
│ Sticker"  ┆ da59-4042 ┆           ┆ — Goblin  ┆   ┆           ┆ , -0.0069 ┆           ┆ 1        │
│ Goblin    ┆ -835f-143 ┆           ┆ Guest     ┆   ┆           ┆ 05, …     ┆           ┆          │
│           ┆ c8d…      ┆           ┆           ┆   ┆           ┆ -0.026…   ┆           ┆          │
│ "Rumors   ┆ cb3587b9- ┆ {2}{B}    ┆ Enchantme ┆ … ┆ ["UST"]   ┆ [-0.00871 ┆ 0.421021  ┆ 2.189697 │
│ of My     ┆ e727-4f37 ┆           ┆ nt        ┆   ┆           ┆ 9, -0.009 ┆           ┆          │
│ Death . . ┆ -b4d6-1ba ┆           ┆           ┆   ┆           ┆ 454, …    ┆           ┆          │
│ ."        ┆ a73…      ┆           ┆           ┆   ┆           ┆ 0.001…    ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Éomer,    ┆ f2c11695- ┆ {3}{R}{W} ┆ Legendary ┆ … ┆ ["LTC"]   ┆ [0.014415 ┆ -1.087738 ┆ -2.87182 │
│ King of   ┆ f22b-44d5 ┆           ┆ Creature  ┆   ┆           ┆ ,         ┆           ┆ 6        │
│ Rohan     ┆ -937c-257 ┆           ┆ — Human   ┆   ┆           ┆ 0.012861, ┆           ┆          │
│           ┆ 8f2…      ┆           ┆ Nob…      ┆   ┆           ┆ …         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0.01945…  ┆           ┆          │
│ Éomer,    ┆ fba68512- ┆ {2}{R}{R} ┆ Legendary ┆ … ┆ ["PLTR",  ┆ [-0.02249 ┆ -1.120117 ┆ -2.85412 │
│ Marshal   ┆ f536-4961 ┆           ┆ Creature  ┆   ┆ "LTR"]    ┆ 2,        ┆           ┆ 6        │
│ of Rohan  ┆ -9e24-563 ┆           ┆ — Human   ┆   ┆           ┆ 0.017429, ┆           ┆          │
│           ┆ 270…      ┆           ┆ Kni…      ┆   ┆           ┆ … 0.0468… ┆           ┆          │
│ Éowyn,    ┆ c1b37891- ┆ {2}{R}{W} ┆ Legendary ┆ … ┆ ["PLTR",  ┆ [-0.03370 ┆ -0.91925  ┆ -3.44824 │
│ Fearless  ┆ 5ed9-47e4 ┆           ┆ Creature  ┆   ┆ "LTR"]    ┆ 8,        ┆           ┆ 2        │
│ Knight    ┆ -8d2f-c2b ┆           ┆ — H

In [5]:
test_matrix = df["embedding"].to_numpy()
test_matrix.shape

(32254, 768)

In [6]:
print(f"{round(test_matrix.nbytes / 1024 / 1024, 2)} MB")

94.49 MB


In [7]:
query_embed = np.random.random(768).astype(np.float32)
query_embed[0:10]

array([0.6111637 , 0.20894407, 0.08792548, 0.05891224, 0.2375212 ,
       0.74691695, 0.38194314, 0.13029811, 0.8787933 , 0.23617905],
      dtype=float32)

## Test Algo (numpy)

Algorithm must return both `idx` of highest `top_k=3` dot products and their `scores`.


In [8]:
result = query_embed @ test_matrix.T
result

array([ 0.34377939,  0.28835738,  0.0170083 , ..., -0.02606963,
        0.3101765 ,  0.20291507], dtype=float32)

In [9]:
k = 3

idx = np.argpartition(result, -k)[-k:]
idx = idx[np.argsort(result[idx])[::-1]]
idx

array([ 8588, 21213,  4898])

In [10]:
score = result[idx]
score

array([0.76883644, 0.76664174, 0.7627919 ], dtype=float32)

## Benchmark


In [11]:
def fast_dot_product(query, matrix):
    dot_products = query @ matrix.T

    idx = np.argpartition(dot_products, -k)[-k:]
    idx = idx[np.argsort(dot_products[idx])[::-1]]

    score = dot_products[idx]

    return idx, score

In [12]:
fast_dot_product(query_embed, test_matrix)

(array([ 8588, 21213,  4898]),
 array([0.76883644, 0.76664174, 0.7627919 ], dtype=float32))

In [ ]:
%%timeit

_ = fast_dot_product(query_embed, test_matrix)

1.08 ms ± 10.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
