In [1]:
import numpy as np

In [2]:
test_matrix = np.random.random((31_650, 768)).astype(np.float32)
test_matrix.shape

(31650, 768)

In [3]:
query_embed = np.random.random(768).astype(np.float32)
query_embed[0:10]

array([0.28700092, 0.5687691 , 0.0591318 , 0.51980084, 0.6304723 ,
       0.21617112, 0.5373042 , 0.44993725, 0.78327405, 0.82358885],
      dtype=float32)

## Test Algo (numpy)

Algorithm must return both `idx` of highest `top_k=3` dot products and their `scores`.


In [4]:
result = query_embed @ test_matrix.T
result

array([185.09572, 189.15286, 186.99785, ..., 191.63419, 191.48468,
       185.2912 ], shape=(31650,), dtype=float32)

In [5]:
k = 3

idx = np.argpartition(result, -k)[-k:]
idx = idx[np.argsort(result[idx])[::-1]]
idx

array([16904, 30142, 22053])

In [6]:
score = result[idx]
score

array([208.74799, 208.39655, 207.74655], dtype=float32)

## Benchmark


In [7]:
def fast_dot_product(query, matrix):
    dot_products = query @ matrix.T

    idx = np.argpartition(dot_products, -k)[-k:]
    idx = idx[np.argsort(dot_products[idx])[::-1]]

    score = dot_products[idx]

    return idx, score

In [8]:
fast_dot_product(query_embed, test_matrix)

(array([16904, 30142, 22053]),
 array([208.74799, 208.39655, 207.74655], dtype=float32))

In [ ]:
%%timeit

_ = fast_dot_product(query_embed, test_matrix)